class_name SettingsOverlay
extends Control

# Settings screen shared by the main menu and the in-game pause menu.
# It saves player preferences through GameState, so the setting survives
# between runs without editing any project files.

const SpaceTheme = preload("res://scripts/ui/space_theme.gd")

@export_file("*.tscn") var return_scene_path: String = "res://scenes/main_menu.tscn"
@export var close_returns_to_scene: bool = true
@export var play_menu_music_on_ready: bool = true

const SETTINGS_BODY: String = """Required Setup
- Open the repository root in Godot 4.6, not the nested game/ folder.
- Run project.godot from the repository root.
- The main menu launches res://scenes/game.tscn.
- Gameplay HUD lives in res://scenes/ui/game_hud.tscn.
- Wave data lives in res://data/waves/wave_01.json through wave_12.json.

Audio
- Use this settings panel to toggle music or change music volume.
- Main menu, wave, boss, and ending music all read the same saved music setting.
- Gameplay feedback sounds are generated by the native SFX bus for now, so buttons, shots, hits, wave clears, and end states still respond while final SFX are being made.

Game Feel
- Screen shake can be disabled while keeping impact flashes and sun breach pulses visible.

Controls
- Towers can be built, upgraded, or sold before and during active waves.
- Mouse wheel zooms, right/middle drag pans, WASD pans, and edge hover pans the camera.
- Center Sun, Home, or 0 returns the camera to the default view.
- End screens support Retry Run and Main Menu, with R and M shortcuts.

Mission Training
- The first gameplay launch shows a guided diagram overlay with arrows for the HUD, tower bay, slots, wave intel, and camera controls.
- Finishing or skipping training saves it as complete in user://settings.cfg so it will not replay automatically.

Native Extension
- GDExtension source lives in gdextension/src.
- Debug rebuild: scons platform=windows target=template_debug arch=x86_64
- Output library: game/bin/perk_the_star.dll
- Entry symbol must stay perk_the_star_init.

Recommended Workflow
1. Edit scenes and scripts from the root project.
2. Validate wave JSON when changing data/waves.
3. Rebuild the native extension only after C++ changes.
4. Run the main menu, then Start Defense to enter the current game scene.

Common Fixes
- Failed to load GDExtension: rebuild and confirm game/bin/perk_the_star.gdextension points to the DLL.
- gdextension_interface.h missing: install or update godot-cpp before building.
- Wave JSON issue: validate the matching file in data/waves.
- Missing music: confirm assets/audio/bgm/final contains main_menu.ogg, wave_01.ogg, wave_02.ogg, wave_03.ogg, and BOSS.ogg."""

@onready var close_button: Button = $settings_panel/settings_margin/settings_box/settings_close
@onready var settings_panel: PanelContainer = $settings_panel
@onready var settings_box: VBoxContainer = $settings_panel/settings_margin/settings_box
@onready var audio_panel: PanelContainer = $settings_panel/settings_margin/settings_box/audio_panel
@onready var settings_scroll: ScrollContainer = $settings_panel/settings_margin/settings_box/settings_scroll
@onready var settings_body: RichTextLabel = $settings_panel/settings_margin/settings_box/settings_scroll/settings_body
@onready var music_volume_slider: HSlider = $settings_panel/settings_margin/settings_box/audio_panel/audio_margin/audio_box/volume_row/music_volume_slider

var tutorial_panel: PanelContainer
var tutorial_status_label: Label
var tutorial_replay_button: Button
var gameplay_panel: PanelContainer
var screen_shake_toggle: CheckButton


func _ready() -> void:
	visible = true
	if play_menu_music_on_ready:
		MusicManager.play_menu_music()
	_build_gameplay_controls()
	_build_tutorial_controls()
	_apply_style()
	close_button.grab_focus()


func show_from_button(_button: Control) -> void:
	close_button.grab_focus()


func close_overlay() -> void:
	if close_returns_to_scene:
		get_tree().change_scene_to_file(return_scene_path)
	else:
		queue_free()


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		close_overlay()


func _apply_style() -> void:
	SpaceTheme.apply_cursor()
	SpaceTheme.apply_fonts(self)
	SpaceTheme.apply_deep_panel(settings_panel, SpaceTheme.COLOR_CYAN)
	SpaceTheme.apply_panel(audio_panel, SpaceTheme.COLOR_GOLD)
	SpaceTheme.apply_panel(gameplay_panel, SpaceTheme.COLOR_CYAN)
	SpaceTheme.apply_panel(tutorial_panel, SpaceTheme.COLOR_CYAN)
	SpaceTheme.apply_scroll_container(settings_scroll)
	SpaceTheme.apply_rich_text_body(settings_body, 16)
	SpaceTheme.apply_slider(music_volume_slider)
	_apply_check_button(screen_shake_toggle)
	SpaceTheme.apply_secondary_button(tutorial_replay_button)
	SpaceTheme.apply_secondary_button(close_button, SpaceTheme.ICON_BACK_PATH)
	settings_scroll.custom_minimum_size.y = 232.0
	if tutorial_status_label != null:
		tutorial_status_label.add_theme_font_size_override("font_size", 13)
		tutorial_status_label.add_theme_color_override("font_color", Color(0.76, 0.88, 0.96, 0.92))
	if tutorial_replay_button != null:
		tutorial_replay_button.add_theme_font_size_override("font_size", 13)
	settings_body.text = SpaceTheme.format_readout_text(SETTINGS_BODY)
	_update_gameplay_status()
	_update_tutorial_status()


func _build_gameplay_controls() -> void:
	if gameplay_panel != null:
		return

	gameplay_panel = PanelContainer.new()
	gameplay_panel.name = "gameplay_panel"
	settings_box.add_child(gameplay_panel)
	settings_box.move_child(gameplay_panel, audio_panel.get_index() + 1)

	var margin: MarginContainer = MarginContainer.new()
	margin.name = "gameplay_margin"
	margin.add_theme_constant_override("margin_left", 18)
	margin.add_theme_constant_override("margin_top", 12)
	margin.add_theme_constant_override("margin_right", 18)
	margin.add_theme_constant_override("margin_bottom", 12)
	gameplay_panel.add_child(margin)

	var row: HBoxContainer = HBoxContainer.new()
	row.name = "gameplay_row"
	row.add_theme_constant_override("separation", 14)
	margin.add_child(row)

	var text_box: VBoxContainer = VBoxContainer.new()
	text_box.name = "gameplay_text"
	text_box.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	text_box.add_theme_constant_override("separation", 3)
	row.add_child(text_box)

	var title_label: Label = Label.new()
	title_label.name = "gameplay_title"
	title_label.text = "Game Feel"
	title_label.add_theme_font_size_override("font_size", 17)
	title_label.add_theme_color_override("font_color", SpaceTheme.COLOR_GOLD)
	text_box.add_child(title_label)

	var body_label: Label = Label.new()
	body_label.name = "gameplay_body"
	body_label.text = "Keep impact flashes on, but choose whether sun breaches shake the camera."
	body_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	body_label.add_theme_font_size_override("font_size", 13)
	body_label.add_theme_color_override("font_color", Color(0.76, 0.88, 0.96, 0.92))
	text_box.add_child(body_label)

	screen_shake_toggle = CheckButton.new()
	screen_shake_toggle.name = "screen_shake_toggle"
	screen_shake_toggle.text = "Screen Shake"
	screen_shake_toggle.custom_minimum_size = Vector2(206.0, 38.0)
	screen_shake_toggle.toggled.connect(_on_screen_shake_toggled)
	row.add_child(screen_shake_toggle)


func _build_tutorial_controls() -> void:
	if tutorial_panel != null:
		return

	tutorial_panel = PanelContainer.new()
	tutorial_panel.name = "tutorial_panel"
	settings_box.add_child(tutorial_panel)
	settings_box.move_child(tutorial_panel, gameplay_panel.get_index() + 1)

	var margin: MarginContainer = MarginContainer.new()
	margin.name = "tutorial_margin"
	margin.add_theme_constant_override("margin_left", 18)
	margin.add_theme_constant_override("margin_top", 12)
	margin.add_theme_constant_override("margin_right", 18)
	margin.add_theme_constant_override("margin_bottom", 12)
	tutorial_panel.add_child(margin)

	var row: HBoxContainer = HBoxContainer.new()
	row.name = "tutorial_row"
	row.add_theme_constant_override("separation", 14)
	margin.add_child(row)

	var text_box: VBoxContainer = VBoxContainer.new()
	text_box.name = "tutorial_text"
	text_box.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	text_box.add_theme_constant_override("separation", 3)
	row.add_child(text_box)

	var title_label: Label = Label.new()
	title_label.name = "tutorial_title"
	title_label.text = "Mission Training"
	title_label.add_theme_font_size_override("font_size", 17)
	title_label.add_theme_color_override("font_color", SpaceTheme.COLOR_GOLD)
	text_box.add_child(title_label)

	tutorial_status_label = Label.new()
	tutorial_status_label.name = "tutorial_status"
	tutorial_status_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	text_box.add_child(tutorial_status_label)

	tutorial_replay_button = Button.new()
	tutorial_replay_button.name = "tutorial_replay_button"
	tutorial_replay_button.text = "REPLAY NEXT LAUNCH"
	tutorial_replay_button.custom_minimum_size = Vector2(206.0, 38.0)
	tutorial_replay_button.pressed.connect(_on_replay_tutorial_pressed)
	row.add_child(tutorial_replay_button)


func _on_replay_tutorial_pressed() -> void:
	GameState.set_tutorial_completed(false)
	_update_tutorial_status()


func _on_screen_shake_toggled(enabled: bool) -> void:
	GameState.set_screen_shake_enabled(enabled)
	_update_gameplay_status()


func _update_gameplay_status() -> void:
	if screen_shake_toggle == null:
		return
	screen_shake_toggle.set_pressed_no_signal(GameState.screen_shake_enabled)


func _update_tutorial_status() -> void:
	if tutorial_status_label == null or tutorial_replay_button == null:
		return
	if GameState.tutorial_completed:
		tutorial_status_label.text = "Completed. Queue it again only when you want the first-run diagram overlay to appear."
		tutorial_replay_button.disabled = false
	else:
		tutorial_status_label.text = "Queued. The diagram overlay will appear on the next gameplay launch, then save when skipped or finished."
		tutorial_replay_button.disabled = true


func _apply_check_button(button: CheckButton) -> void:
	if button == null:
		return
	button.add_theme_font_override("font", load(SpaceTheme.FONT_BUTTON_PATH) as Font)
	button.add_theme_font_size_override("font_size", 13)
	button.add_theme_color_override("font_color", SpaceTheme.COLOR_TEXT)
	button.add_theme_color_override("font_hover_color", Color(1.0, 0.96, 0.74, 1.0))
	button.add_theme_color_override("font_pressed_color", Color(1.0, 0.96, 0.74, 1.0))
	button.mouse_default_cursor_shape = Control.CURSOR_POINTING_HAND
